# Generated by Django 4.0.2 on 2022-02-10 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('comment', models.CharField(max_length=255, verbose_name='Comment')),
                ('text', models.TextField(verbose_name='Text')),
                ('priority', models.IntegerField(choices=[(1, 'Обовязково'), (2, 'Бажано'), (3, 'По можливості')], verbose_name='Приоритет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
