# Generated by Django 4.0.2 on 2022-02-10 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('to_Do', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=255, unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='text',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
    ]
